experiment:
  duration: 200 # seconds
  trialLength: 5 # seconds
  closedLoop: 1

  channels:
  # Just a letter will filter all channels with that letter
    - F
    - C
    - A
    - T
    - P
    - O
    # - PO7
    # - PO3
    # - POz
    # - PO4
    # - PO8
    # - O1
    # - Oz
    # - O2

  commandMapping:
    top: 0
    left: 1
    down: 2
    right: 3
    nothing: 4
    middle: 5

  stimulusFrequencies:
    # actual freq = 60/f -> 3 => 60/3 = 20hz
    top: 6     # 10 Hz - 20Hz
    left: 8    # 7.5 Hz - 15 Hz
    bottom: 11 # 5.4545 - 10.9
    right: 14  # 4.2857 - 8.5714

ui:
  fullscreen: 0
  windowSize:
    width: 1920 #1024
    height: 1080 #768 
  
  monitorRefreshRate: 60
  refreshThreshold: 0.01 # seconds (warning if threshold is reached from refresh) # Default = 120% of refresh rate

  loggingLevel: DATA # ERROR, WARNING, DATA, EXP, INFO and DEBUG
  # Add stimulus positions?

classifier:
  labelFile: 'labels.txt'
  maxSampleLength: 1500
  confidence_level: 0.6

streams:
  decoder:
    inlet_names:
      # eeg: ActiChamp
      # eeg: Micromed
      eeg: gtec_outlet
      ui: UiOutput 
      # - ActiChamp # Used for previous SSVEP
      # - UiOutput
      # - Micromed # used for MockAmp
    outlet_names: # Decoder
    # TODO: add outlet specifications to config
      - UiInput

  SSVEPui:
    inlet_names: 
      - UiInput
    outlet_names:
      - UiOutput
 